name: CI

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint with flake8
        run: |
          pipx run flake8

      - name: Lint with mypy
        run: |
          pipx run mypy mousebender

      - name: Check format with Black
        run: |
          pipx run black --check .

      - name: Can be built
        run: |
          pipx run flit build

  tests:
    name: Test Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install Flit
        run: |
          python -m pip install flit

      - name: Install dependencies
        run: |
          flit install --extras test

      - name: Test with pytest
        run: |
          pytest --cov
