name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt
    - name: Lint with mypy
      run: |
        python -m mypy mousebender
    - name: Format with Black
      run: |
        python -m black --check .
    - name: Test with pytest
      run: |
        python -m pytest --cov
